[package]
name = "mimir"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.197"
serde_traitobject = "0.2.8"

[dev-dependencies]
serde_json = "1.0.114"
serde = { version = "1.0.197", features = ["derive"] }
