[package]
name = "helheim"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = "2.0.52"
skuld = { path = "../skuld", default-features = false, features = ["bail"] }

[lib]
proc-macro = true
